import { CustomerTypes } from "./types/Customers.types";
export const CustomersMock: CustomerTypes[] = [
  {
    id: 1,
    key: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "234 567 8900",
    address: "123 Main St, Springfield, USA",
    // createdAt: new Date(),
    // updatedAt: new Date(),
  },
  {
    id: 2,
    key: "2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "234 567 8901",
    address: "456 Elm St, Springfield, USA",
  },
  {
    id: 3,
    key: "3",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    phone: "234 567 8902",
    address: "789 Oak St, Springfield, USA",
  },
  {
    id: 4,
    key: "4",
    name: "Bob Brown",
    email: "bob.brown@example.com",
    phone: "234 567 8903",
    address: "321 Pine St, Springfield, USA",
  },
  {
    id: 5,
    key: "5",
    name: "Acer Swift X SFX14-41G",
    email: "acer.swift@example.com",
    phone: "234 567 8904",
    address: "654 Maple St, Springfield, USA",
  },
];
